# fly.toml file generated for webserver-co-ban on 2023-06-11T15:08:18+07:00

app = "webserver-co-ban"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "hkg"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
