# fly.toml file generated for nodejs-app on 2023-04-19T15:52:39+07:00

app = "nodejs-app"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
